---
# Mirror from the entitled registry if not airgapped and entitlement key found in vault
- name: Mirror images for Cloud Pak for Data from entitled to private registry {{ current_cp4d_cluster.image_registry_name }}
  include_role: 
    name: cp4d-mirror-images
  vars:
    _p_mirror_motion: entitled-to-private
    _p_current_cp4d_cluster: "{{ current_cp4d_cluster }}"
when: 
- not (cpd_airgap | bool)

# Mirror from portable registry if airgapped
- name: Mirror images for Cloud Pak for Data from portable to private registry {{ current_cp4d_cluster.image_registry_name }}
  include_role: 
    name: cp4d-mirror-images
  vars:
    _p_mirror_motion: portable-to-private
    _p_current_cp4d_cluster: "{{ current_cp4d_cluster }}"
  when: cpd_airgap | bool
