- name: Retrieve default certification
  ansible.builtin.include_role:
    name: common
    tasks_from: retrieve-default-certification
  vars:
    common_crt_output_to_var: "tls_crt"
    common_key_output_to_var: "tls_key"
    common_ca_output_to_var: "ca_crt"
        
# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=secrets-creating-custom-bpc-workforce-secret
# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=secrets-creating-custom-bai-secret
- name: Prepare yaml file for BAI Secret
  ansible.builtin.template:
    src: bai/bai-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/bai-secret.yaml"
    mode: u+rwx

- name: Add BAI Secret
  kubernetes.core.k8s:
    state: present
    src: "{{ cp4ba_output_directory }}/bai-secret.yaml"
