# Based on https://www.ibm.com/docs/en/cloud-paks/1.0?topic=configuration-operational-datastore
# Username change is not described
- name: Prepare yaml file for admin OpenSearch user Secret
  ansible.builtin.template:
    src: iaf/opensearch-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/opensearch-secret.yaml"
    mode: u+rwx

- name: Add admin OpenSearch user Secret
  kubernetes.core.k8s:
    state: present
    src: "{{ cp4ba_output_directory }}/opensearch-secret.yaml"
