---
- set_fact:
    _cartridge_options: '{{ {} | combine({_cartridge_name: _p_installation_options}) }}'

- set_fact:
    _added_installation_options: "{{ {} | combine({_p_section: _cartridge_options}) }}"
