---
- name: Set target directory for portable registry to {{ status_dir }}/work/registry-storage
  ansible.builtin.replace:
    path: /opt/ansible/etc/registryv2-config.yml
    regexp: 'rootdirectory: .*'
    replace: 'rootdirectory: {{ status_dir }}/work/registry-storage'

- name: Run the entrypoint, which will start the portable registry
  shell:
    /usr/local/bin/entrypoint > {{ status_dir }}/log/olm-utils-entrypoint.log 2>&1
  async: 1500000
  poll: 0

- name: Wait until portable registry is available at port 12443
  wait_for:
    host: "127.0.0.1"
    port: 12443
    timeout: 30
