---
- set_fact:
    _tmp_cartridges: []

- set_fact:
    _tmp_cartridges: >-
      {{ _tmp_cartridges
        + [ _tmp_cartridge ] }}
  vars:
    _tmp_cartridge: >-
      {{ _apply_cartridges 
        | selectattr('name','eq',item['name']) 
        | list 
        | first 
        | default([]) }}
  loop: "{{ _apply_cartridges }}"
  when:
  - (item.Expected_Version | default('')) != 'N/A'
  - (item.Status | default('')) != (item.cr_status_completed | default('')) or
      (item.upgrade_cartridge | default(False) | bool) or
      not (item.allow_optimize | default(True) | bool)

- set_fact:
    _apply_cartridges: "{{ _tmp_cartridges }}"