---
- name: Delete secret Validate mandatory variables are defined
  assert:
    that:
      - hashicorp_vault_address is defined
      - hashicorp_secret_name_path is defined

- name: Get all versions for secret {{ hashicorp_secret_name_path }}
  community.hashi_vault.vault_read:
    url: "{{ hashicorp_vault_address }}"
    path: "secret/metadata/{{ secret_group}}/{{ _secret_name }}"
    auth_method: token
    token: '{{ _hashicorp_ephemeral_token | default(VAULT_PASSWORD) }}'
  register: _hashicorp_read_secret_results
  failed_when: false

- set_fact:
    _secret_versions: "{{ range(1,_hashicorp_read_secret_results.data.data.current_version+1) }}"
  when: _hashicorp_read_secret_results.data.data.current_version | default(0) != 0
  
- name: Delete secret {{ hashicorp_secret_name_path }}
  community.hashi_vault.vault_kv2_delete:
    url: "{{ hashicorp_vault_address }}"
    path: "{{ hashicorp_secret_name_path }}"
    auth_method: token
    token: '{{ _hashicorp_ephemeral_token | default(VAULT_PASSWORD) }}'
    versions: "{{ _secret_versions | default(omit) }}"