---
- name: Delete secret from Hashicorp Vault
  include_tasks: delete-secret-hashicorp.yml
  when: vault.vault_type == 'hashicorp-vault'

- name: Delete secret from Vault IBMCloud
  include_tasks: delete-secret-ibmcloud.yml
  vars:
    ibmcloud_vault_address: "{{ vault.vault_url }}"
    ibm_cloud_secret_name: "{{ secret_name }}"
  when: vault.vault_type == 'ibmcloud-vault'

- name: Delete secret from Vault file
  include_tasks: delete-secret-file.yml
  when: vault.vault_type == 'file-vault'

- name: Record deleted secret for {{ secret_group }}
  lineinfile:
    path: "{{ status_dir}}/tmp/cpd-vault-delete.out"
    line: "{{ secret_group }} secrets that were deleted:"
    create: true

- name: Write secret name to cpd-vault-delete.out
  lineinfile:
    path: "{{ status_dir }}/tmp/cpd-vault-delete.out"
    line: "- {{ secret_name }}"