---
- name: Has Secret from Vault IBM Cloud
  block:
    - name: Validate mandatory variables are defined for Vault IBM Cloud
      assert:
        that:
          - secret_name is defined
          - secret_group is defined

    - name: Fail if a secret field was specified for a vault other than Hashicorp
      fail:
        msg: "Secret name {{ secret_name }} can only have a secret field specification for Hashicorp Vault"
      when: secret_name is search(",")

    - name: Has secret in Vault IBMCloud
      include_tasks: has-secret-ibmcloud.yml
      vars:
        ibmcloud_vault_address: "{{ vault.vault_url }}"
        ibm_cloud_secret_name: "{{ secret_name }}"
  when: "vault.vault_type == 'ibmcloud-vault'"