---
- set_fact:
    _storage_type: 'pwx'
  when: "'px-db' in _storage_class_names"

- set_fact:
    _storage_type: 'ibm-classic-storage'
  when: "'ibmc-file-gold-gid' in _storage_class_names"

- set_fact:
    _storage_type: 'nfs'
  when: "'managed-nfs-storage' in _storage_class_names"

- name: Find the first rbd storage class
  set_fact:
    _ceph_rbd_storage_class: "{{ _storage_classes.resources | selectattr('provisioner', 'in', _v_ceph_rbd_provisioners) | map(attribute='metadata.name') | list | first | default('') }}"

- set_fact:
    _storage_type: 'odf'
  when: _ceph_rbd_storage_class != ''

- set_fact:
    _storage_type: 'aws-elastic'
  when: "'efs-nfs-client' in _storage_class_names"

- name: Fail if storage type could not be detected
  fail:
    msg: "Storage type could not be detected for storage_type auto. Make sure that the cluster has NFS, ODF (OCS), Elastic, IBM-FDF, or Portworx storage classes."
  when: _storage_type == 'auto'

- name: Show detected storage type when set to auto
  debug:
    msg: "Detected storage type: {{ _storage_type }}"