---
- name: Get secret Validate mandatory variables are defined
  assert:
    that:
      - hashicorp_vault_address is defined
      - hashicorp_secret_name_path is defined

- name: List secrets for {{ hashicorp_secret_name_path }}
  community.hashi_vault.vault_list:
    url: "{{ hashicorp_vault_address }}"
    path: "{{ hashicorp_secret_name_path }}"
    auth_method: token
    token: '{{ VAULT_PASSWORD }}'
  register: hashicorp_vault_list_secrets_result

- name: Result of listing secrets
  debug:
    var: hashicorp_vault_list_secrets_result

- set_fact:
    secret_list: "{{ hashicorp_vault_list_secrets_result['data']['data']['keys'] | default([]) | list }}"
