---
- name: Check if {{ _p_current_cp4d_cluster.project }} still exists
  kubernetes.core.k8s_info:
    kind: namespace
    name: "{{ _p_current_cp4d_cluster.project }}"
    api_version: v1
  register: _cp4d_namespace

- include_tasks: cp4d-cluster-delete.yml
  when: (_cp4d_namespace.resources | default([])) != []